### ISSUE TITLE
New Classifier: PHPUnit Tests

### ISSUE THREAD

**Issue by stefanzweifel** [stefanzweifel/laravel-stats#80]
For the next version, we would like to detect PHPUnit Tests and display their stats.

Detecting a PHPUnit Test should be easy as a Test has to extend the `PHPUnit\Framework\TestCase` class.

### TODOs

- [ ] Add a new PHPUnitClassifier [here](https://github.com/stefanzweifel/laravel-stats/tree/master/src/Classifiers)
- [ ] Add Logic to new Classifier. [Here is an example](https://github.com/stefanzweifel/laravel-stats/blob/master/src/Classifiers/ModelClassifier.php)
- [ ] Add the new Classifier to the `CLASSIFIERS` constant [here](https://github.com/stefanzweifel/laravel-stats/blob/master/src/Classifiers/Classifier.php#L9)
- [ ] Write Tests to make sure that PHPUnit Tests are correctly classified. [Here you find examples](https://github.com/stefanzweifel/laravel-stats/blob/master/tests/ClassifierTest.php)

We're open for Pull Requests 👋
